services:
  api:
    build:
      context: .
      dockerfile: IaC\Dockerfile.api
    image: dp-stock/api:dev
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - agent
    networks: [ appnet ]

  agent:
    build:
      context: .
      dockerfile: IaC\Dockerfile.agent
    image: dp-stock/agent:dev
    networks: [ appnet ]

  frontend:
    build:
      context: .
      dockerfile: frontend\Dockerfile
    image: dp-stock/frontend:dev
    ports:
      - "3000:80"
    depends_on:
      - api
    networks: [ appnet ]

networks:
  appnet:
    driver: bridge