services:
  api:
    build:
      context: .
      dockerfile: IaC\Dockerfile.api
    image: dp-stock/api:dev
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - agent
      - mongodb
      - redis
    networks: [ appnet ]

  agent:
    build:
      context: .
      dockerfile: IaC\Dockerfile.agent
    image: dp-stock/agent:dev
    networks: [ appnet ]

  frontend:
    build:
      context: .
      dockerfile: frontend\Dockerfile
    image: dp-stock/frontend:dev
    ports:
      - "3000:80"
    depends_on:
      - api
    networks: [ appnet ]
    
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-stockadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-stockpassword}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-stock_assistant}
    volumes:
      - mongodb_data:/data/db
      - ./data/migration/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks: [ appnet ]
    
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    volumes:
      - redis_data:/data
    networks: [ appnet ]

networks:
  appnet:
    driver: bridge
    
volumes:
  mongodb_data:
  redis_data: