apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dp-stock.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels: { app: {{ include "dp-stock.fullname" . }}, tier: api }
  template:
    metadata:
      labels:
        app: {{ include "dp-stock.fullname" . }}
        tier: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet: { path: /api/health, port: 5000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /api/health, port: 5000 }
            initialDelaySeconds: 15
          env:
            - name: PYTHONUNBUFFERED
              value: "1"