apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dp-stock.fullname" . }}-agent
spec:
  replicas: {{ .Values.replicaCount.agent }}
  selector:
    matchLabels: { app: {{ include "dp-stock.fullname" . }}, tier: agent }
  template:
    metadata:
      labels:
        app: {{ include "dp-stock.fullname" . }}
        tier: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
          ports:
            - containerPort: 7000
          readinessProbe:
            httpGet: { path: /health, port: 7000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 7000 }
            initialDelaySeconds: 15