apiVersion: v1
kind: Service
metadata:
  name: {{ include "dp-stock.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type | default "ClusterIP" }}
  selector: { app: {{ include "dp-stock.fullname" . }}, tier: frontend }
  ports:
    - port: {{ .Values.service.frontend.port | default 80 }}
      targetPort: 80