apiVersion: v1
kind: Service
metadata:
  name: {{ include "dp-stock.fullname" . }}-api
spec:
  type: {{ .Values.service.api.type }}
  selector: { app: {{ include "dp-stock.fullname" . }}, tier: api }
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 5000